// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeFTwWC5RYDRV4cQk2suF1CMwYLtri5bI',
    appId: '1:762112032862:web:8769857f928d0d402af4cf',
    messagingSenderId: '762112032862',
    projectId: 'fitnesstracker-8a21d',
    authDomain: 'fitnesstracker-8a21d.firebaseapp.com',
    storageBucket: 'fitnesstracker-8a21d.appspot.com',
    measurementId: 'G-0CSYG7Q7PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY-oVxH676GXXI0G09tsfd0LywT6zt3ZI',
    appId: '1:762112032862:android:7b0888a4b032e7a62af4cf',
    messagingSenderId: '762112032862',
    projectId: 'fitnesstracker-8a21d',
    storageBucket: 'fitnesstracker-8a21d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvd0zMy0dEo0RM6bOebsqAmM_F9Povimc',
    appId: '1:762112032862:ios:87863ec2a7b4c8502af4cf',
    messagingSenderId: '762112032862',
    projectId: 'fitnesstracker-8a21d',
    storageBucket: 'fitnesstracker-8a21d.appspot.com',
    iosBundleId: 'com.example.flutterFitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvd0zMy0dEo0RM6bOebsqAmM_F9Povimc',
    appId: '1:762112032862:ios:fef4d2af0c79297b2af4cf',
    messagingSenderId: '762112032862',
    projectId: 'fitnesstracker-8a21d',
    storageBucket: 'fitnesstracker-8a21d.appspot.com',
    iosBundleId: 'com.example.flutterFitness.RunnerTests',
  );
}
